# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            99 Summers
tagline:          'My thoughts on technology'
description:      'My thoughts on technology.'
url:              http://jfmcdowell.com
baseurl:          /

author:
  name:           'Justin McDowell'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/jfmcdowell
